<?php

namespace Database\Seeders;

use App\Models\SDM;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SdmTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        SDM::truncate();

        SDM::create(array(
            array(
                'id' => 1,
                'id_sdm' => 'b27d3846-f8c2-470b-9b64-bd2dab5e8db4',
                'nama_sdm' => 'ABBYZAR AGGASI',
                'nidn' => '0818019001',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 2,
                'id_sdm' => '4733ea8c-86d1-4b31-bb3c-81ccc7790a3a',
                'nama_sdm' => 'ABDUL HADI ILMAN',
                'nidn' => '0830088701',
                'nip' => '',
                'nama_status_aktif' => 'TUGAS BELAJAR',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 3,
                'id_sdm' => 'c27990b7-4950-4457-bcac-2b49a986dfd7',
                'nama_sdm' => 'ABDUL SALAM',
                'nidn' => '0802128602',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 4,
                'id_sdm' => '8c5412ac-5e1b-4312-95ad-3a5a9bb262c3',
                'nama_sdm' => 'ACUH DHARMAWAN JUNAIDI',
                'nidn' => '7700018335',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 5,
                'id_sdm' => '04d5b96a-0bcd-4012-81dd-e827a11cf186',
                'nama_sdm' => 'ADELIA ELVIANTARI',
                'nidn' => '0826069502',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 6,
                'id_sdm' => '5ca3ff10-a1bc-45ac-819c-d1eb01074181',
                'nama_sdm' => 'ADI MAWARDIN',
                'nidn' => '0822109002',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 7,
                'id_sdm' => 'c0f5a6e8-2e8a-4581-a374-06d381ae5776',
                'nama_sdm' => 'ADI SURIYADIN',
                'nidn' => '0829079601',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 8,
                'id_sdm' => 'ac6297ce-e01d-4e11-8df2-a18004f8ef70',
                'nama_sdm' => 'AGUS SALAM',
                'nidn' => '9908430592',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 9,
                'id_sdm' => '8633b271-649b-4b5f-b3cd-951b60186f47',
                'nama_sdm' => 'AGUS SANTOSO',
                'nidn' => '0801089501',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 10,
                'id_sdm' => '6ccabf53-bc1c-4cf0-bc6b-4feb24dc6bc4',
                'nama_sdm' => 'AHMAD JAYA',
                'nidn' => '0806128302',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 11,
                'id_sdm' => '7a43cb00-4ace-4c74-85ba-c9c901d1c586',
                'nama_sdm' => 'AHMAD JIBRAIL',
                'nidn' => '0828048402',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 12,
                'id_sdm' => 'cc1812dd-06df-4ba0-9620-3c7014cc2454',
                'nama_sdm' => 'AHMAD JULIANSYAH',
                'nidn' => '7700017859',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 13,
                'id_sdm' => '1057aa5c-8039-4590-b066-2952840848a9',
                'nama_sdm' => 'AHMAD REZA JATNIKA',
                'nidn' => '0830129301',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 14,
                'id_sdm' => 'bf500375-0383-4f56-a274-b4c822e246dd',
                'nama_sdm' => 'AISYAH PUTRI RAWE MAHARDIKA',
                'nidn' => '0817089401',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 15,
                'id_sdm' => '9f8d18e9-905d-48cf-9bbf-0925e02c98d9',
                'nama_sdm' => 'AKA KURNIA SF',
                'nidn' => '0826097501',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 16,
                'id_sdm' => '79702834-ea3d-413e-adcf-446f6ed7b2c8',
                'nama_sdm' => 'ALAMSYAH',
                'nidn' => '7700017818',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 17,
                'id_sdm' => 'a5ae8f34-be5e-4341-bd2f-e4732893de15',
                'nama_sdm' => 'ALDRIN',
                'nidn' => '0824126901',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 18,
                'id_sdm' => 'be5b7c76-4a10-4573-8e64-fd4629c35e14',
                'nama_sdm' => 'ALI BUDHI KUSUMA',
                'nidn' => '0828028803',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 19,
                'id_sdm' => 'a1a82b4e-054a-4736-a55a-131049066221',
                'nama_sdm' => 'AMRI HIDAYAT',
                'nidn' => '0810079001',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 20,
                'id_sdm' => 'fb86dd00-6659-48cf-97de-c64e956910ba',
                'nama_sdm' => 'ANDI RUSNI',
                'nidn' => '0824037801',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 21,
                'id_sdm' => 'f16206ed-c209-4671-9668-3ba554a4a45c',
                'nama_sdm' => 'ANDRI SAHRUL ANAM',
                'nidn' => '7700017827',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 22,
                'id_sdm' => '4ec9acec-09c7-47ea-abb4-a74b06ff5381',
                'nama_sdm' => 'ANDY TIRTA',
                'nidn' => '0812048501',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 23,
                'id_sdm' => 'b34d060e-3384-40f9-8735-82fa13c92968',
                'nama_sdm' => 'ANITA GUSMIARTI',
                'nidn' => '7700022995',
                'nip' => '-',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 24,
                'id_sdm' => '9b134710-7e9a-4743-9d4b-3dacff75a539',
                'nama_sdm' => 'ANWAR SA',
                'nidn' => '0810117001',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 25,
                'id_sdm' => '6b46e4e5-e450-4565-891a-05982d1fa46b',
                'nama_sdm' => 'APRIADI',
                'nidn' => '0819098602',
                'nip' => '',
                'nama_status_aktif' => 'TUGAS BELAJAR',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 26,
                'id_sdm' => '32fa6528-2425-46d3-82cf-4e3eed7c544f',
                'nama_sdm' => 'ARIE KASMITA',
                'nidn' => '7700019255',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 27,
                'id_sdm' => '605be507-775a-494a-9f5d-531ba0ccdb2c',
                'nama_sdm' => 'ARIS SUGIARTO',
                'nidn' => '0827127002',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 28,
                'id_sdm' => '3b30635c-bc35-4bee-a831-c96801f050f7',
                'nama_sdm' => 'ARNI FITRIANA',
                'nidn' => '7700012852',
                'nip' => '199004262018102294',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 29,
                'id_sdm' => 'f4207c5d-87a6-417d-b4f2-3e8b6f27f174',
                'nama_sdm' => 'ARNI LATIFAH',
                'nidn' => '7700017830',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 30,
                'id_sdm' => '5c45bcfc-4263-4cf8-a7f8-171b69e36550',
                'nama_sdm' => 'ARYA ZULFIKAR AKBAR',
                'nidn' => '0805079303',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 31,
                'id_sdm' => '2c877b8d-78ba-4258-9588-fca00857f677',
                'nama_sdm' => 'ASWAR TAHIR',
                'nidn' => '0806019402',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 32,
                'id_sdm' => 'f11ef02f-4b23-4c52-bc45-a63ce55724d5',
                'nama_sdm' => 'ASYWENDI RUKINI',
                'nidn' => '0821039101',
                'nip' => '',
                'nama_status_aktif' => 'TUGAS BELAJAR',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 33,
                'id_sdm' => 'a6390f12-393a-4596-9587-b3bce2efedb1',
                'nama_sdm' => 'AYU LEVIA TRYANA',
                'nidn' => '0802039401',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 34,
                'id_sdm' => 'e47a9417-6abf-4cf7-a917-484f3464d7fc',
                'nama_sdm' => 'AYUNING ATMASARI',
                'nidn' => '0812098602',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 35,
                'id_sdm' => 'd5074114-6346-4390-8aa7-3725e115f11a',
                'nama_sdm' => 'CHAIRUL ANAM AFGANI',
                'nidn' => '0805039301',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 36,
                'id_sdm' => '6f2499d3-1a4b-4c35-a5af-6e86aa55e0b2',
                'nama_sdm' => 'DEDY DHARMAWANSYAH',
                'nidn' => '0827098601',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 37,
                'id_sdm' => '4db2ca9e-d785-4022-a63b-cce054fd0fc2',
                'nama_sdm' => 'DEDY HERIWIBOWO',
                'nidn' => '8925400020',
                'nip' => '610019656',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 38,
                'id_sdm' => '17eeca6e-78e8-49d5-93e3-903849bc9202',
                'nama_sdm' => 'DEDY SUKREYADI',
                'nidn' => '7700018247',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 39,
                'id_sdm' => 'ef98fc8f-ea73-4631-a929-5e29aa4a9c59',
                'nama_sdm' => 'DENNY HAMBALI',
                'nidn' => '0827018402',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 40,
                'id_sdm' => '96a1199c-6ad2-457e-b4eb-eb1f0c04046a',
                'nama_sdm' => 'DESI MAULIDYAWATI',
                'nidn' => '0816129001',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 41,
                'id_sdm' => '79e040ba-9391-4fb2-883f-3b6271c1b285',
                'nama_sdm' => 'DEVI TANGGASARI',
                'nidn' => '0819029001',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 42,
                'id_sdm' => '64ba6fa1-bcaf-41e3-afb3-b92a87a2f4d5',
                'nama_sdm' => 'DEWI WAHYUNI',
                'nidn' => '7700018346',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 43,
                'id_sdm' => 'c650deb5-b53b-4c03-9db9-014809edc4ed',
                'nama_sdm' => 'DIAH ANGGERAINI HASRI',
                'nidn' => '0825058502',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 44,
                'id_sdm' => 'c6299f23-1021-4b5b-97d2-7ae7ce09d7d2',
                'nama_sdm' => 'DIAH INTAN SYAHFITRI',
                'nidn' => '0816129003',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 45,
                'id_sdm' => 'ab141232-cede-4de5-bb77-4cbf0160b7ac',
                'nama_sdm' => 'DIMASTUTI PUTRI KARYANINGTIYAS',
                'nidn' => '7700018161',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 46,
                'id_sdm' => 'c59ef432-9dd1-438b-b0d4-69aba3ced524',
                'nama_sdm' => 'DINAR SUKSMAYU SAPUTRI',
                'nidn' => '0728048501',
                'nip' => '',
                'nama_status_aktif' => 'TUGAS BELAJAR',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 47,
                'id_sdm' => '2dbbf278-4ceb-4efd-a394-63090590b061',
                'nama_sdm' => 'DINDA FARDILA',
                'nidn' => '0813089401',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 48,
                'id_sdm' => '6eb94396-9caa-44fa-bbd2-1305a92a09c5',
                'nama_sdm' => 'DWI ARIYANTI',
                'nidn' => '0804018003',
                'nip' => '-',
                'nama_status_aktif' => 'TUGAS BELAJAR',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 49,
                'id_sdm' => '520c036e-9118-4f8c-a386-bd091161b4f7',
                'nama_sdm' => 'DWI FORTUNA',
                'nidn' => '7700021980',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 50,
                'id_sdm' => '10940207-f808-4dca-b8be-efbc95b50302',
                'nama_sdm' => 'EDI IRAWAN',
                'nidn' => '0826048402',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 51,
                'id_sdm' => 'fcba1606-3d2f-4477-b378-6d2f1b8e768e',
                'nama_sdm' => 'EDY ZATRIADY',
                'nidn' => '9908419929',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 52,
                'id_sdm' => 'ed79712a-2eab-4838-8e22-1d9c6ffff82f',
                'nama_sdm' => 'EFAN YUDHA WINATA',
                'nidn' => '0811089101',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 53,
                'id_sdm' => 'd53e745f-aa86-49b3-88c1-54c3856199b5',
                'nama_sdm' => 'EKA ARDIANSYAH',
                'nidn' => '0825128401',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 54,
                'id_sdm' => 'a40fff34-3145-457f-8fba-67757e10edad',
                'nama_sdm' => 'EKA HARYANTI',
                'nidn' => '0810098001',
                'nip' => '-',
                'nama_status_aktif' => 'TUGAS BELAJAR',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 55,
                'id_sdm' => '9f5363f0-00fe-4657-8448-10054b9bca7c',
                'nama_sdm' => 'EKA YUNI SUMARNINGSIH',
                'nidn' => '7700018240',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 56,
                'id_sdm' => 'ce84c79f-b7d3-4bbc-87bb-e36d02f4d771',
                'nama_sdm' => 'EKI RUSKARTINA',
                'nidn' => '0808049002',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 57,
                'id_sdm' => '92c43834-ddc3-4356-a077-f7fe69e94bb6',
                'nama_sdm' => 'EKO WIJAYA',
                'nidn' => '0801019501',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 58,
                'id_sdm' => 'e9056bc8-9742-421c-bcb6-9999ea9e89a5',
                'nama_sdm' => 'EMSAL YANUAR',
                'nidn' => '0804019001',
                'nip' => '',
                'nama_status_aktif' => 'TUGAS BELAJAR',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 59,
                'id_sdm' => '7cc1e588-2a62-4158-ac54-dd556f6a2988',
                'nama_sdm' => 'ERA RAHMAWATI PUTRI',
                'nidn' => '7700019273',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 60,
                'id_sdm' => '94402006-b08e-4693-a555-e812a2b6c8b9',
                'nama_sdm' => 'ERI SASMITA SUSANTO',
                'nidn' => '0804059203',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 61,
                'id_sdm' => 'd4d8ed1c-e73e-42c8-bd54-307120161d41',
                'nama_sdm' => 'ERI SOFIATRY',
                'nidn' => '0811108505',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 62,
                'id_sdm' => '397eaa21-7507-4e35-818c-3dd26c6d05ab',
                'nama_sdm' => 'ERLIYANI KURNIA',
                'nidn' => '7700018131',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 63,
                'id_sdm' => '0c1f2006-141a-425e-8b71-a9d9f241be87',
                'nama_sdm' => 'ERNAWATI',
                'nidn' => '7700022988',
                'nip' => '-',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 64,
                'id_sdm' => 'b4417bca-6f71-4e19-b815-7bdec7272ed2',
                'nama_sdm' => 'ERWIN MARDINATA',
                'nidn' => '0807039502',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 65,
                'id_sdm' => 'a49939b8-8b71-411e-bbba-524bcb4b07ec',
                'nama_sdm' => 'ETI KURNIATI',
                'nidn' => '0807118906',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 66,
                'id_sdm' => 'ef5a1dc3-9b61-459f-a4e2-f9aacce02a7f',
                'nama_sdm' => 'EVA JULIANI',
                'nidn' => '7700018784',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 67,
                'id_sdm' => 'a35e115b-3226-4dee-9c53-cb4b89509939',
                'nama_sdm' => 'FADHLI DZIL IKRAM',
                'nidn' => '0811088902',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 68,
                'id_sdm' => 'c1d55be9-c379-4893-b61b-6316a0604fcf',
                'nama_sdm' => 'FADLI FATURRAHMAN',
                'nidn' => '0828067602',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 69,
                'id_sdm' => '1f5c5afd-3ac8-4a5e-8b76-808c3cdfe8dc',
                'nama_sdm' => 'FAHLIA',
                'nidn' => '0830109103',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 70,
                'id_sdm' => 'e088f7e4-5541-4a34-a2c0-302d0e04d810',
                'nama_sdm' => 'FAHRI HAMDANI',
                'nidn' => '0813118701',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 71,
                'id_sdm' => '6aab70ca-d878-4e48-af87-d566633262c5',
                'nama_sdm' => 'FAHRI JAYADI',
                'nidn' => '7700022986',
                'nip' => '-',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 72,
                'id_sdm' => '8aaffe0b-e8ef-409b-bdec-ec9cc65d58ac',
                'nama_sdm' => 'FAHRUL AMRI',
                'nidn' => '7700018777',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 73,
                'id_sdm' => '932d98a2-3bc1-43ff-8d4c-bda2206c0550',
                'nama_sdm' => 'FAHRUNNISA',
                'nidn' => '0819019003',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 74,
                'id_sdm' => '025622d6-b024-431e-91a1-7d71654931e6',
                'nama_sdm' => 'FARIDA IDIFITRIANI',
                'nidn' => '9908419502',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 75,
                'id_sdm' => '5c844a5b-0db1-4692-b41f-923bd7544da8',
                'nama_sdm' => 'FATURRAHMAN',
                'nidn' => '7700017848',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 76,
                'id_sdm' => '3561027a-4bc9-410b-9913-dfea6d9f555e',
                'nama_sdm' => 'FAUZI WIDYAWATI',
                'nidn' => '0805029201',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 77,
                'id_sdm' => 'b2e9d162-b72d-4604-8050-319524f1f781',
                'nama_sdm' => 'FENDY MARADITA',
                'nidn' => '0822099002',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 78,
                'id_sdm' => 'bbb3cbbc-947f-4d1b-bc85-07db6fc6e66d',
                'nama_sdm' => 'FIRDA WAHYU NINGTIYAS',
                'nidn' => '7700019172',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 79,
                'id_sdm' => '88685ec1-b616-424f-9259-465874e3e1bd',
                'nama_sdm' => 'FITRA HASRI ROSANDI',
                'nidn' => '0812109001',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 80,
                'id_sdm' => '0187e64f-a68f-44dc-9f8f-b320718d29d1',
                'nama_sdm' => 'FITRAH DANY',
                'nidn' => '7700022992',
                'nip' => '-',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 81,
                'id_sdm' => 'd9b1cffd-c834-421f-9513-d2183ec504a9',
                'nama_sdm' => 'FITRAYUDDIN',
                'nidn' => '8951350022',
                'nip' => '610035109',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 82,
                'id_sdm' => 'be588091-0587-42db-a547-4f20c4991f11',
                'nama_sdm' => 'FITRIA PERMATACITA',
                'nidn' => '0825090701',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 83,
                'id_sdm' => '4656709d-c825-418d-b1f2-b8c67efe37e1',
                'nama_sdm' => 'GALIH EL FIKRI',
                'nidn' => '0804069402',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 84,
                'id_sdm' => '0e6281d7-5b32-4d52-8619-e86023066780',
                'nama_sdm' => 'HANIFA SRI NURYANI',
                'nidn' => '0808088401',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 85,
                'id_sdm' => '34242e05-40cf-41fb-9ab9-2ec5c61ea292',
                'nama_sdm' => 'HANINDHIA',
                'nidn' => '7700018213',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 86,
                'id_sdm' => '383830bf-5956-447d-88af-e17e52bc2e99',
                'nama_sdm' => 'HARDIAN REZA DHARMAYANDA',
                'nidn' => '0820018303',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 87,
                'id_sdm' => 'c24e0390-d243-4f67-852f-c50361711b92',
                'nama_sdm' => 'HARJITO',
                'nidn' => '8873790019',
                'nip' => '196104191991031001',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'PNS Diperbantukan',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 88,
                'id_sdm' => 'bc57e9a8-9e7d-4673-8d40-f676dbca9918',
                'nama_sdm' => 'HARTINI',
                'nidn' => '0821048603',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 89,
                'id_sdm' => 'be2332a1-3d31-4236-9ca7-cc23b2acbeff',
                'nama_sdm' => 'HENDRAYADI',
                'nidn' => '7700017728',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 90,
                'id_sdm' => '12b9afb8-8eb2-43db-9f96-8bca5a5872b4',
                'nama_sdm' => 'HERFANDI',
                'nidn' => '0823049301',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 91,
                'id_sdm' => '0cd7481a-f1f4-4499-9749-e3b749181e94',
                'nama_sdm' => 'HERI MURTAWAN',
                'nidn' => '0808088903',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 92,
                'id_sdm' => '6cfee1c7-a31e-4c9d-be26-59c23b303a55',
                'nama_sdm' => 'HERMANSYAH',
                'nidn' => '0811109001',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 93,
                'id_sdm' => 'ab780add-aa23-4b6b-85bf-dab801067d41',
                'nama_sdm' => 'HERY KRISNA HERMAWAN',
                'nidn' => '7700018778',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 94,
                'id_sdm' => '21ae61f4-9f4d-4b9d-ad69-dec843b6f47b',
                'nama_sdm' => 'HUSNI',
                'nidn' => '0812037801',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 95,
                'id_sdm' => '329e92ea-d9fe-4a61-ac2d-4ee201dda41c',
                'nama_sdm' => 'IHLANA NAIRFANA',
                'nidn' => '0805049102',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 96,
                'id_sdm' => '4987a1bc-9c65-424e-b457-2e02b5478a5d',
                'nama_sdm' => 'IHWAN KHULDI',
                'nidn' => '7700013494',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 97,
                'id_sdm' => 'd1662e1c-e640-48a1-985e-77275dea39da',
                'nama_sdm' => 'IKSAN ADIASA',
                'nidn' => '0808039401',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 98,
                'id_sdm' => '5ded2223-3d3d-4cd4-bbab-8e041f1aec6c',
                'nama_sdm' => 'I MADE WIDIARTA',
                'nidn' => '0813018701',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 99,
                'id_sdm' => 'd25d3396-bf4f-47e3-a309-c7f116f2d6eb',
                'nama_sdm' => 'IMAMMUL INSAN',
                'nidn' => '0812119001',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 100,
                'id_sdm' => '29da6779-274c-47a1-8bc3-4dfaa879c460',
                'nama_sdm' => 'IMAM MUNANDAR',
                'nidn' => '0801029501',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 101,
                'id_sdm' => '74aaf8bc-d760-4d12-a4ca-87a0f0b14be2',
                'nama_sdm' => 'INDAH NURULITA',
                'nidn' => '7700019331',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 102,
                'id_sdm' => '955f18bf-1ded-48cc-b4b6-96018508abd1',
                'nama_sdm' => 'INDRA DARMAWAN',
                'nidn' => '0809018802',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 103,
                'id_sdm' => '106a1e14-5b51-4633-a4ea-3baab7b57a99',
                'nama_sdm' => 'I PUTU WIDIANTARA',
                'nidn' => '0826048903',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 104,
                'id_sdm' => '32682923-f443-48f8-8440-57b1e9ad98da',
                'nama_sdm' => 'IRA RAUDATUL JANNAH',
                'nidn' => '7700018245',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 105,
                'id_sdm' => '2b35b350-cd2d-4c25-a93d-63e1bc70763c',
                'nama_sdm' => 'IRAWATI',
                'nidn' => '7700017845',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 106,
                'id_sdm' => 'c490f5c7-75ee-4bba-bd5c-ee465fd0537b',
                'nama_sdm' => 'IRWANDI',
                'nidn' => '7700017849',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 107,
                'id_sdm' => '9567cdc4-3325-4142-a096-56709946e5da',
                'nama_sdm' => 'IRWANSYAH',
                'nidn' => '0810109103',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 108,
                'id_sdm' => 'da4f1d09-fe34-4595-a192-bfbf1aad44c9',
                'nama_sdm' => 'ISMI MASHABAI',
                'nidn' => '0417048502',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 109,
                'id_sdm' => 'ed6a444e-10a2-4dc9-a004-15e6a5b2bc38',
                'nama_sdm' => 'IVON ARISANTI',
                'nidn' => '0821098101',
                'nip' => '',
                'nama_status_aktif' => 'TUGAS BELAJAR',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 110,
                'id_sdm' => '3199c7e7-c22b-4213-8541-d938ba64f74e',
                'nama_sdm' => 'IZZUL ISLAM',
                'nidn' => '0811028902',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 111,
                'id_sdm' => 'd16d4d84-ed96-4fa7-b6bd-561e95c7622a',
                'nama_sdm' => 'JANNATUN ALIYAH',
                'nidn' => '7700018307',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 112,
                'id_sdm' => '182afdb4-0063-491c-a9dd-8761765d4bd5',
                'nama_sdm' => 'JAYANTI MANDASARI',
                'nidn' => '0801099201',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 113,
                'id_sdm' => '1c5fcb27-53a5-4648-bd95-08e7a481a56f',
                'nama_sdm' => 'JUNAIDIN',
                'nidn' => '0830119002',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 114,
                'id_sdm' => 'bdc479e4-ac1c-47f5-a92d-82845bba20a7',
                'nama_sdm' => 'KHOLIS ABDU SUBAGIA',
                'nidn' => '7700022993',
                'nip' => '-',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 115,
                'id_sdm' => '3e16e49a-2c9c-4ee2-bc50-a24c822634dd',
                'nama_sdm' => 'KHOTIBUL UMAM',
                'nidn' => '0816079002',
                'nip' => '',
                'nama_status_aktif' => 'TUGAS BELAJAR',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 116,
                'id_sdm' => 'fba59ddf-dcbf-42eb-81d1-e5bdcbeb2789',
                'nama_sdm' => 'KIKI YULIANTO',
                'nidn' => '0803078703',
                'nip' => '0',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 117,
                'id_sdm' => '7fa779e6-f786-4af2-ace5-2904eb8f150d',
                'nama_sdm' => 'KOKO HERMANTO',
                'nidn' => '0818128802',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 118,
                'id_sdm' => '8d4ed0f4-09d3-4a26-94b7-d769a877034c',
                'nama_sdm' => 'KUSDIANAWATI',
                'nidn' => '1306029101',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 119,
                'id_sdm' => 'e07d3ecb-3fa4-477e-a7e0-de1bd1121b0d',
                'nama_sdm' => 'LALU AHMAD TAUBIH',
                'nidn' => '0813128902',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 120,
                'id_sdm' => '4fd9ba1d-91b7-4ded-9eab-a68f169de6ee',
                'nama_sdm' => 'LALU HERI RIZALDI',
                'nidn' => '0806079301',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 121,
                'id_sdm' => '9551f89f-dee7-430b-b841-31704725bce3',
                'nama_sdm' => 'LALU SUHAIMI',
                'nidn' => '0826128803',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 122,
                'id_sdm' => '845222d3-0906-43fe-8060-e67b45c18fdf',
                'nama_sdm' => 'LEGGINA REZZY VANGGY',
                'nidn' => '7700019258',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 123,
                'id_sdm' => 'b4075b3d-6702-46a8-b18e-625591df510a',
                'nama_sdm' => 'LILI SUHARLI',
                'nidn' => '0809089001',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 124,
                'id_sdm' => 'be45cfee-86c5-4d05-a325-95c906b24102',
                'nama_sdm' => 'LUKMANUL HAKIM',
                'nidn' => '0812128703',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 125,
                'id_sdm' => '263500e8-285a-409c-919f-b079770bca9a',
                'nama_sdm' => 'LUKMANUL HAKIM',
                'nidn' => '0804088801',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 126,
                'id_sdm' => 'abd763f1-24a4-4417-94ed-9c26ac35896b',
                'nama_sdm' => 'MASYITAH AULIA',
                'nidn' => '0803119403',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 127,
                'id_sdm' => '6ad44b2d-b9e7-4952-9609-09f81866a26f',
                'nama_sdm' => 'MAYA FITRIANI',
                'nidn' => '9908419751',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 128,
                'id_sdm' => '31de77ee-485f-4e12-8dad-38eafc2497d5',
                'nama_sdm' => 'MEGA TRISHUTA PATHIASSANA',
                'nidn' => '0804078902',
                'nip' => '',
                'nama_status_aktif' => 'TUGAS BELAJAR',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 129,
                'id_sdm' => '3d366a35-ae08-4328-998a-53677fde7a8b',
                'nama_sdm' => 'MIETRA ANGGARA',
                'nidn' => '0807039002',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 130,
                'id_sdm' => 'aaf4ef31-bfd8-41bd-9f7e-a96a013a19c4',
                'nama_sdm' => 'MIFTAHUL ARZAK',
                'nidn' => '0805129001',
                'nip' => '',
                'nama_status_aktif' => 'TUGAS BELAJAR',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 131,
                'id_sdm' => 'bcb6a6e1-4405-4eb6-a5c2-e8a1729d1cfb',
                'nama_sdm' => 'MIFTA PRATIWI RACHMAN',
                'nidn' => '0822118601',
                'nip' => '',
                'nama_status_aktif' => 'TUGAS BELAJAR',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 132,
                'id_sdm' => '51761bc0-c446-40ee-aeb9-5285c1d0e4c9',
                'nama_sdm' => 'MIKHRATUNNISA',
                'nidn' => '0814038902',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 133,
                'id_sdm' => '97df4b39-0ca5-46a4-89f3-bc1b85ea30ec',
                'nama_sdm' => 'MILA HIDAYATULLAH',
                'nidn' => '7700019329',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 134,
                'id_sdm' => '247c1cd9-2772-4840-8896-75d4b149171e',
                'nama_sdm' => 'M. JULKARNAIN',
                'nidn' => '0806079202',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 135,
                'id_sdm' => '850f100b-a91d-49fe-bcd0-fec677373ce6',
                'nama_sdm' => 'M. RIZKY ADITIYA PRATAMA',
                'nidn' => '7700018357',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 136,
                'id_sdm' => '60a43ad9-5ed0-435a-a7cb-1fdb46100ab2',
                'nama_sdm' => 'M. SYUKRON ANSHORI',
                'nidn' => '0829089102',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 137,
                'id_sdm' => 'b8363865-7d31-42d5-8e33-55061819f12f',
                'nama_sdm' => 'MUAMMAR KHADAFIE',
                'nidn' => '0808068603',
                'nip' => '',
                'nama_status_aktif' => 'TUGAS BELAJAR',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 138,
                'id_sdm' => 'd33e090f-eedf-429e-8119-a7d17684642e',
                'nama_sdm' => 'MUHAMAD HIDAYAT',
                'nidn' => '0803097102',
                'nip' => '-',
                'nama_status_aktif' => 'TUGAS BELAJAR',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 139,
                'id_sdm' => 'dde0aa6d-ebb8-475e-9585-f6be26bace3f',
                'nama_sdm' => 'MUHAMMAD FAUZI',
                'nidn' => '7700013479',
                'nip' => '199512042019041308',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 140,
                'id_sdm' => 'a6113a4d-e2bd-4818-866d-d3aeb1e013a8',
                'nama_sdm' => 'MUHAMMAD HAIKAL ABDURACHMAN',
                'nidn' => '0805049402',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 141,
                'id_sdm' => '01250a4b-7c7d-4514-9f2d-72f21e8c587b',
                'nama_sdm' => 'MUHAMMAD HIDAYATULLAH',
                'nidn' => '0802098901',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 142,
                'id_sdm' => '5707effb-6234-4e5a-8d68-8b9bf13eb7e2',
                'nama_sdm' => 'MUHAMMAD HILMY ALFARUQI',
                'nidn' => '0830078603',
                'nip' => '',
                'nama_status_aktif' => 'TUGAS BELAJAR',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 143,
                'id_sdm' => 'eca34cd2-49db-43a2-bca1-5f334a944742',
                'nama_sdm' => 'MUHAMMAD IKBAL',
                'nidn' => '7700017844',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 144,
                'id_sdm' => '5644ee89-b2a0-4e80-9af4-1e71f4216725',
                'nama_sdm' => 'MUHAMMAD IQBAL',
                'nidn' => '9908430591',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 145,
                'id_sdm' => 'c64d00db-9344-47df-8e5b-0cfd4dae295d',
                'nama_sdm' => 'MUHAMMAD JARNAWANSYAH',
                'nidn' => '0815028803',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 146,
                'id_sdm' => '7e0f97a6-ab1e-45a7-812a-9327234ba77a',
                'nama_sdm' => 'MUHAMMAD NUR FIETROH',
                'nidn' => '0816028604',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 147,
                'id_sdm' => 'dbf909ae-4969-41f5-b7e4-dc733078f228',
                'nama_sdm' => 'MUHAMMAD NURJIHADI',
                'nidn' => '0810049001',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 148,
                'id_sdm' => 'e3676a0f-7383-4897-80f2-03c1851ca59c',
                'nama_sdm' => 'MUHAMMAD RAFI\'I SANJANI',
                'nidn' => '0807078902',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 149,
                'id_sdm' => '90693710-aab4-4cd0-b4c4-be101eaa7c8d',
                'nama_sdm' => 'MUHAMMAD SALEH',
                'nidn' => '8893000016',
                'nip' => '196308161992031004',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 150,
                'id_sdm' => 'd028b607-2390-4ca0-8851-73e5ecabcbbe',
                'nama_sdm' => 'MUH. FAHRUDDIN',
                'nidn' => '0816048703',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 151,
                'id_sdm' => '6b9de31d-b8c1-4103-b287-dcbc84efc981',
                'nama_sdm' => 'MUJIBUR RAHMAT',
                'nidn' => '0810058701',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 152,
                'id_sdm' => '2fcc1e5c-01d2-4b97-8c51-ab54fdd0736a',
                'nama_sdm' => 'MUSTARAM',
                'nidn' => '7700018211',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 153,
                'id_sdm' => 'd25309fa-3689-47a1-bd6f-28424161b666',
                'nama_sdm' => 'NAWASSYARIF',
                'nidn' => '0805058903',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 154,
                'id_sdm' => 'fef6b30e-0666-411a-b153-377662e5b265',
                'nama_sdm' => 'NORA DERY SOFYA',
                'nidn' => '0816069501',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 155,
                'id_sdm' => 'fdd68fa3-83ab-4caa-b925-6fcac182b703',
                'nama_sdm' => 'NOVA ADHITYA ANANDA',
                'nidn' => '0826118801',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 156,
                'id_sdm' => '1aef2c68-f40a-4232-821d-609d2ce8b87c',
                'nama_sdm' => 'NOVA ARYANTO',
                'nidn' => '0825118303',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 157,
                'id_sdm' => 'd5ab5110-c3d1-4789-9e7d-05a91f3820dd',
                'nama_sdm' => 'NOVIDA HELLEINE PUTRI',
                'nidn' => '0813119301',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 158,
                'id_sdm' => 'b0239348-eb85-4594-8129-bc541a22145b',
                'nama_sdm' => 'NURAMALIYAH',
                'nidn' => '0812019601',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 159,
                'id_sdm' => 'f09cf638-7df6-45ad-9f12-85d207b39fc0',
                'nama_sdm' => 'NURFADLIYAH',
                'nidn' => '0821069302',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 160,
                'id_sdm' => '866e08e2-12b0-47f0-bbd5-c4007427ab46',
                'nama_sdm' => 'NURHADI IHWANI',
                'nidn' => '0805089002',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 161,
                'id_sdm' => '99baf8d6-7e49-43e4-b14d-17ab6e545353',
                'nama_sdm' => 'NURLAILY',
                'nidn' => '7700018209',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 162,
                'id_sdm' => '666314d3-dd65-4969-922b-ff26993c8909',
                'nama_sdm' => 'NURNANINGSIH',
                'nidn' => '7700018787',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 163,
                'id_sdm' => 'b544f237-a438-4e8f-b8a6-871e4ed5bbe5',
                'nama_sdm' => 'NURUL AMRI KOMARUDIN',
                'nidn' => '0813099302',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 164,
                'id_sdm' => 'a2119124-343e-472e-951c-9aaf6590fe25',
                'nama_sdm' => 'NURUL HUDANINGSIH',
                'nidn' => '0826028902',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 165,
                'id_sdm' => '461e05d0-f657-4184-b174-a898798db452',
                'nama_sdm' => 'NURUL IZZATI',
                'nidn' => '0806038802',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 166,
                'id_sdm' => '50dd9a94-7da4-465d-aa99-9907936af050',
                'nama_sdm' => 'OFI HIDAYAT',
                'nidn' => '0803119201',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 167,
                'id_sdm' => '074c75af-7617-4662-9337-4a2864652c82',
                'nama_sdm' => 'PARIS ALI TOPAN',
                'nidn' => '0803089002',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 168,
                'id_sdm' => 'b1de06fd-c31f-4642-a2ee-a6e97783e3a4',
                'nama_sdm' => 'PRAMUDYA BAGAS UTAMA',
                'nidn' => '0818048604',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 169,
                'id_sdm' => '9af68a44-f060-4a6a-bbd1-1133f0953dfd',
                'nama_sdm' => 'PRATIWI SAKTI',
                'nidn' => '0801109001',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 170,
                'id_sdm' => '79c621e7-4310-4221-a168-4245ebf0c593',
                'nama_sdm' => 'RABIATUL',
                'nidn' => '7700019179',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 171,
                'id_sdm' => 'b345f527-c622-4ab5-bfe4-4aa89edb8cdd',
                'nama_sdm' => 'RADYUM IKONO',
                'nidn' => '0824128802',
                'nip' => '',
                'nama_status_aktif' => 'TUGAS BELAJAR',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 172,
                'id_sdm' => '6b3fd44c-7188-4d67-a564-fa7efa9c08a0',
                'nama_sdm' => 'RAMA SUGANDHI',
                'nidn' => '0828048701',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 173,
                'id_sdm' => '75a1c52a-d624-4968-8954-e643d51f44d6',
                'nama_sdm' => 'RANDHY ADHI KAMULA',
                'nidn' => '0806059301',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 174,
                'id_sdm' => '6af55a19-5059-4766-9ffe-d62b03e6530b',
                'nama_sdm' => 'RATNA NURMALITA SARI',
                'nidn' => '0805019402',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 175,
                'id_sdm' => 'a3550ca3-ef79-431d-a63b-ba246ba5baba',
                'nama_sdm' => 'REZA HANDIKA',
                'nidn' => '7700017822',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 176,
                'id_sdm' => 'c01f7c9f-bd0c-46f0-aac3-e3f1f221c4d2',
                'nama_sdm' => 'REZA MUHAMMAD RIZQI',
                'nidn' => '0824059201',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 177,
                'id_sdm' => 'bb8f7085-5cb0-4db3-b982-2d02529e4d3d',
                'nama_sdm' => 'RIRI RIMBUN ANGGIH CHAIDIR',
                'nidn' => '0810088802',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 178,
                'id_sdm' => '2bd5683d-939c-4e41-8542-96ce3638e837',
                'nama_sdm' => 'RITA DESIASNI',
                'nidn' => '0816129002',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 179,
                'id_sdm' => '73c5d91b-d4d0-4958-821b-2edd4788081c',
                'nama_sdm' => 'RODIANTO',
                'nidn' => '0808078101',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 180,
                'id_sdm' => 'ccd3fd73-3508-40ce-afe8-c810be6209c1',
                'nama_sdm' => 'ROHANA',
                'nidn' => '7700016288',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 181,
                'id_sdm' => '8b95c740-47a8-4f8d-8bc2-ed8ee1206cb2',
                'nama_sdm' => 'RONI HARTONO',
                'nidn' => '0806058703',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 182,
                'id_sdm' => '2165f129-cb12-4e7c-bb67-1191e358b390',
                'nama_sdm' => 'ROZZY APRIRACHMAN',
                'nidn' => '0814049302',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 183,
                'id_sdm' => '4139bff1-7c49-47ce-933a-810f45f3c8e0',
                'nama_sdm' => 'RUDI MASNIADI',
                'nidn' => '0810078501',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 184,
                'id_sdm' => '34fe5c57-2500-4595-a359-0779cd8cee66',
                'nama_sdm' => 'RYAN SUARANTALLA',
                'nidn' => '0801039001',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 185,
                'id_sdm' => 'e58cf48b-5a2d-42d6-9318-c64b3ac3bf36',
                'nama_sdm' => 'SABRI BALAFIF',
                'nidn' => '0704048804',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 186,
                'id_sdm' => '9644c62d-c0da-409f-81c9-6b8a4add6e3d',
                'nama_sdm' => 'SAHRI YANTI',
                'nidn' => '0803058802',
                'nip' => '',
                'nama_status_aktif' => 'TUGAS BELAJAR',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 187,
                'id_sdm' => 'b32bc3aa-6355-49ac-bc78-5ce650278159',
                'nama_sdm' => 'SAMUYUS NEALMA',
                'nidn' => '0828089002',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 188,
                'id_sdm' => '890b64b4-2b36-4482-9326-bbf0cff61313',
                'nama_sdm' => 'SAUSAN NAFISAH',
                'nidn' => '0824039002',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 189,
                'id_sdm' => '80f90cf9-a0a3-4532-8d4e-9d320608c66b',
                'nama_sdm' => 'SERLI OKTAPIANI',
                'nidn' => '0801109302',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 190,
                'id_sdm' => 'f282a942-4bda-4178-9944-8b43214f6134',
                'nama_sdm' => 'SHAFWAN AMRULLAH',
                'nidn' => '0828089104',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 191,
                'id_sdm' => 'ab315405-b040-493d-b6e8-ed60126d16b9',
                'nama_sdm' => 'SHERWIN ARY BUSMAN',
                'nidn' => '0813059003',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 192,
                'id_sdm' => '0333a394-8520-467e-8f49-f2b1e1f0c89e',
                'nama_sdm' => 'SHINTA ESABELLA',
                'nidn' => '0814078603',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 193,
                'id_sdm' => 'ccd1ab64-dc2d-43b5-bfee-9607d442c8b5',
                'nama_sdm' => 'SILVIA FIRDA UTAMI',
                'nidn' => '0825049202',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 194,
                'id_sdm' => 'fde0392c-cc12-467d-b693-280bb493a984',
                'nama_sdm' => 'SOPYAN ALI ROHMAN',
                'nidn' => '0820039002',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 195,
                'id_sdm' => '9a83c479-b507-491a-8064-69c24fa03c98',
                'nama_sdm' => 'SRI ANDRIANI',
                'nidn' => '0806098601',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 196,
                'id_sdm' => '480636a5-c924-40ab-a957-d35baeb253c0',
                'nama_sdm' => 'SRI BUKYA',
                'nidn' => '7700018205',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 197,
                'id_sdm' => '4ad77dc5-5d59-47aa-96fd-7644875de92b',
                'nama_sdm' => 'SRIYATUN',
                'nidn' => '0810017806',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 198,
                'id_sdm' => '46db3b29-71f8-48a6-bda4-6e7314b2a3a1',
                'nama_sdm' => 'SUDRAJAT MARTADINATA',
                'nidn' => '0823067902',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 199,
                'id_sdm' => '28248b98-e072-4a24-a862-860f273084bd',
                'nama_sdm' => 'SUPARMAN',
                'nidn' => '0807108701',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 200,
                'id_sdm' => '352e07c1-61f5-4dc3-a972-6df799ed13c2',
                'nama_sdm' => 'SURYA YULYANTO',
                'nidn' => '7700019794',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 201,
                'id_sdm' => '0eff8a58-bf25-426f-9a6d-faf3482ade6b',
                'nama_sdm' => 'SUTARJON',
                'nidn' => '7700018306',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 202,
                'id_sdm' => '0c4c0ead-d729-4a16-8539-5e154aea0948',
                'nama_sdm' => 'SYAMSUL BAHTIAR',
                'nidn' => '0822018904',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 203,
                'id_sdm' => 'af9909ed-1435-4872-98c9-a87f69454bb8',
                'nama_sdm' => 'SYAMSUL HIDAYAT',
                'nidn' => '0824038901',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 204,
                'id_sdm' => 'f1254d63-1d53-4449-b7e8-c9675ac580ce',
                'nama_sdm' => 'TARYONO',
                'nidn' => '0801046501',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 205,
                'id_sdm' => 'ef25ad69-ec81-48cb-8e8f-2e1c809e78d4',
                'nama_sdm' => 'TAUFIKKURRAHMAN',
                'nidn' => '7700017858',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 206,
                'id_sdm' => '88add6cc-11b7-42fe-9234-b4a55e3c7152',
                'nama_sdm' => 'TEGUH IMAN HADINULLAH',
                'nidn' => '7700017759',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 207,
                'id_sdm' => 'bbb53bfc-6dda-4f36-8207-174586cc7207',
                'nama_sdm' => 'TITI ANDRIANI',
                'nidn' => '0803018501',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 208,
                'id_sdm' => '2b06287a-5ea3-464a-bab8-43f757d75a61',
                'nama_sdm' => 'TOMY DWI CAHYONO',
                'nidn' => '0828099001',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 209,
                'id_sdm' => '35e4977e-e128-49c0-a7c6-819c5735c161',
                'nama_sdm' => 'TOPAN RAHMATUL IMAN',
                'nidn' => '0822079202',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 210,
                'id_sdm' => '00b65c38-38b1-4bb3-82bc-5689bf50e80f',
                'nama_sdm' => 'TRI SUSILAWATI',
                'nidn' => '0813068901',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 211,
                'id_sdm' => 'eecb5615-0e86-4b0c-a3cc-3cca87303f6d',
                'nama_sdm' => 'UMAR',
                'nidn' => '0822077301',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 212,
                'id_sdm' => '49606eb2-a934-452f-b0fd-d5b700a5554b',
                'nama_sdm' => 'VENI RORI SETIAWATI',
                'nidn' => '0824028501',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 213,
                'id_sdm' => '8c6e38db-b253-4bbd-a724-0aedb2ea30ab',
                'nama_sdm' => 'VINA FITRIANA',
                'nidn' => '0819058601',
                'nip' => '',
                'nama_status_aktif' => 'TUGAS BELAJAR',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 214,
                'id_sdm' => '844ee40c-6177-4b6c-9cf7-56da87bbce3a',
                'nama_sdm' => 'VIVIN NILA RAKHMATULLAH',
                'nidn' => '0821068603',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 215,
                'id_sdm' => '946dd70f-c758-4b57-8d8f-2078df8d827c',
                'nama_sdm' => 'WAWAT RODIAHWATI',
                'nidn' => '0831058902',
                'nip' => '',
                'nama_status_aktif' => 'TUGAS BELAJAR',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 216,
                'id_sdm' => '588ca920-6c12-47a0-8e4b-225422053d0e',
                'nama_sdm' => 'WIDYAWATI LESTARI',
                'nidn' => '7700019259',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 217,
                'id_sdm' => 'de3ceeae-1176-4533-bc75-22b4b4ef6f4f',
                'nama_sdm' => 'WILIA ISMIYARTI',
                'nidn' => '0821058201',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 218,
                'id_sdm' => '8b11fffc-90f1-4c17-8299-a73c543dab20',
                'nama_sdm' => 'WIN ARIGA MANSUR MALONGA',
                'nidn' => '0809128802',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 219,
                'id_sdm' => '097e1fb5-097d-438a-aba0-dc44ad1a2c78',
                'nama_sdm' => 'WINDA ANGGRAINI',
                'nidn' => '7700016579',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 220,
                'id_sdm' => '6079fcf1-1b5e-49dc-96fe-d5ed5edafb7c',
                'nama_sdm' => 'WINDA MEIRIASTUTI',
                'nidn' => '0817059101',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 221,
                'id_sdm' => '2740d95b-1fa9-4cc7-8515-eb33eb550299',
                'nama_sdm' => 'WIRENTAKE',
                'nidn' => '0803039101',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 222,
                'id_sdm' => 'bd83ef91-666a-4080-ad37-271c3663fbfa',
                'nama_sdm' => 'WIRYA SARWANA',
                'nidn' => '0808099001',
                'nip' => '',
                'nama_status_aktif' => 'TUGAS BELAJAR',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 223,
                'id_sdm' => '6373891b-bb7a-477f-a66d-00f3dbd9b713',
                'nama_sdm' => 'WIWIN YULIANA',
                'nidn' => '7700019185',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 224,
                'id_sdm' => 'd1c49df0-1ad5-48a5-9be6-550cc1b50a86',
                'nama_sdm' => 'YANA KARISMA',
                'nidn' => '0808089102',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 225,
                'id_sdm' => '9b452d59-8524-4949-ad89-f8fc814285e2',
                'nama_sdm' => 'YAYAT OKTARIADI',
                'nidn' => '7700018250',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 226,
                'id_sdm' => 'dbdc0c55-f1f6-4a9f-9018-bfde2487235f',
                'nama_sdm' => 'YOLLI EKA PUTRI',
                'nidn' => '0815038203',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 227,
                'id_sdm' => 'b3e1ff50-9e1a-4321-9d99-e98ea2539d1b',
                'nama_sdm' => 'YOSSY DWI ERLIANA',
                'nidn' => '0815067701',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 228,
                'id_sdm' => 'dd1be504-7028-402e-8ced-3b43b34ded18',
                'nama_sdm' => 'YUDI MULYANTO',
                'nidn' => '0829118502',
                'nip' => '',
                'nama_status_aktif' => 'IJIN BELAJAR',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 229,
                'id_sdm' => '788e8723-fa27-4528-8b40-a6fbeb54288f',
                'nama_sdm' => 'YULIADI',
                'nidn' => '0805018301',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 230,
                'id_sdm' => '2fab9426-a235-4830-b735-d7d10b38e99e',
                'nama_sdm' => 'YUNANRI.W',
                'nidn' => '0805068304',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 231,
                'id_sdm' => '1e8ea031-b6c3-424a-864c-43f5c22e2eba',
                'nama_sdm' => 'YUNI YOLANDA',
                'nidn' => '0815069501',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 232,
                'id_sdm' => '4c663e0f-699c-45d5-9172-326fdaff2cd0',
                'nama_sdm' => 'ZAINUDDIN',
                'nidn' => '9908000289',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 233,
                'id_sdm' => '2c96fa8d-14ab-4b83-a83a-d291a0b22d91',
                'nama_sdm' => 'ZAINUDDIN HUSAINY',
                'nidn' => '0811117301',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 234,
                'id_sdm' => '70614608-3a7a-4b6a-9922-4967aef71f3c',
                'nama_sdm' => 'ZULFIQAR RAHADIAN TAMIN',
                'nidn' => '7700019213',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
            array(
                'id' => 235,
                'id_sdm' => '9a9482ea-9b09-4604-9148-f66a746103ef',
                'nama_sdm' => 'ZULKIEFLIMANSYAH',
                'nidn' => '8896130017',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Dosen',
            ),
            array(
                'id' => 236,
                'id_sdm' => 'a7d73f3e-df9d-4ec5-ae71-c437e58d533b',
                'nama_sdm' => 'ZULVIANA KAYANTI',
                'nidn' => '7700018782',
                'nip' => '',
                'nama_status_aktif' => 'Aktif',
                'nama_status_pegawai' => 'NON PNS',
                'jenis_sdm' => 'Tenaga Kependidikan',
            ),
        ));
    }
}
